services:
  spendid.api:
    image: ${DOCKER_REGISTRY-}spendidapi
    container_name: Spendid.Api
    environment:
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      
      - Authorization__AllowedEmails=${ALLOWED_EMAILS}

      - ConnectionStrings__Database=Host=spendid.db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
    build:
      context: .
      dockerfile: Spendid.Api/Dockerfile
    depends_on:
      spendid.db:
        condition: service_healthy

  spendid.db:
    image: postgres:latest
    container_name: Spendid.Db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.containers/database:/var/lib/postgresql
    ports:
      - ${DB_HOST_PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
